version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: npm install
      - run: npm run testMac
          name: Run tests
          command: npm run testMac
