version: 2
jobs:
  build:
    machine: true
    working_directory: ~/userService
    docker: # run the steps with Docker
      - image: circleci/node:8.0
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run testMac
